###########################
# Config definition
###########################


# Directory to save the output files (like log.txt and model weights)
output_dir: "./output"
# Path to a directory where the files were saved previously
resume: False
# Set seed to negative value to randomize everything
# Set seed to positive value (>0) to use a fixed seed
seed: -1
# Set GPU
# Set N_GPU_USE to 0 if there is no GPU
# Set N_GPU_USE to positive value to use GPUs
use_cuda: True
n_gpu_use: 1
# Print detailed information
# E.g. trainer, dataset, and backbone
verbose: True
# settings for loggers
exp_group: 'individual'
exp_desc_notes: 'date_'


defaults:
  - _self_
  - inputs: default_inputs
  - dataset: default_dataset
  - model: baseline_model
  - trainer: baseline_trainer

